# The name of this site
# This text displays in the back-office and
# can be used in templates through the site.name global variable
name: "Tgv"

# An array of domain aliases for the site
# This option is for sites on multi-site engines
# domains: [www.example.com, example.com]

# An array of locales (languages) the site is available in
# The locale listed first is the site's default locale
# Locales are specified using ISO language codes
# Possible locales include: en, de, fr, pl, pt-BR, it, nl, nb, es, ru, et, ja, zh-CN
locales: [en,fr]

# The site's timezone
# This converts the server's time to the site's time zone in templates
# The TimeZone class from Rail's ActiveSupport is used to interpret the string
# Sample timezone strings: Tokyo, Beijing, Moscow, Cairo, Paris, Pacific Time (US & Canada)
timezone: Paris

# For SEO purposes, sites may wish to add a relevant string to the <title> tag
# And include <meta type="keywords"> and <meta type="description">
# For this purpose you can set values for these variables here
# They can be accessed in templates through the site.seo_title, site.meta_keywords, and site.meta_description variables
seo_title: Tgv
meta_keywords: "locomotivecms templates gists snippets trips tricks"
meta_description: "LocomotiveCMS Gists"

# You can control the display of the "Properties" section in the back-office
# metafields_ui:
#   label: Store settings # use a hash for localized versions
#   icon: shopping-cart # FontAwesome icons without the leading "fa-" string.
#   hint: "Lorem ipsum..."

# Each site can have its own set of custom properties organized in namespaces.
# First, define namespaces and their fields in the config/metafields_schema.yml file.
# Finally, set default values below as described in the example.
# You can access them in your liquid templates and snippets:
#   {{ site.metafields.<namespace>.<field> }}
#
# Example:
#
# metafields:
#   shop:
#     address: 700 South Laflin Street
#   theme:
#     background_image: "/samples/background.png"

algolia:
    application_id: XXXXXXx
    api_key: 46b05xxxxxxxxxxxxxxxxxxxxxx
    reset: false
